server:
  port: 9999
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fares?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sspu.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: false

wx:
  appid: dfd
  secret: 12345

path:
 filePath: /Users/zhanglu/Pictures/

jwt:
 config:
  key: userLogin
  failure: 3600000
